#!/usr/bin/env python3
"""The verifier.

Design rules, each of which closes a way a candidate could be scored correct
without having solved anything:

  * **The instance is generated by the grader, not shipped.**  There is no
    input file on disk for a candidate to edit, and no committed expected
    output to copy.  Both are functions of ``--seed``.

  * **The expected answer never exists where the candidate can reach it.**
    It is streamed out of the reference implementation *after* the candidate
    has exited, and compared record-by-record.  Nothing is written to disk, so
    there is no golden file to read, symlink to, or race.

  * **Candidate stdout is data, never a verdict.**  The candidate's stdout is
    redirected to a file opened by the grader before privileges are dropped,
    ``O_WRONLY`` and mode 0600 owned by root -- so the candidate can write its
    answer but cannot read back what it wrote, and cannot print a line that the
    grader mistakes for a result.  A candidate that prints ``PASS`` has simply
    emitted an unparseable first record.

  * **Exit status is necessary but never sufficient.**  ``exit 0`` with no
    output fails on record count; a partial answer fails at the first
    differing record.

  * **The memory ceiling is enforced, not measured.**  ``RLIMIT_AS`` is set
    soft==hard before ``execvp``, so exceeding it kills the candidate rather
    than producing a number the grader has to interpret.  Measured RSS is
    reported for the record, but the verdict does not depend on the grader
    reading it correctly.
"""

import argparse
import errno
import io
import json
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "task"))

import reference          # noqa: E402
import sandbox            # noqa: E402
import generate           # noqa: E402

DEFAULT_ADDRESS_SPACE = 32 << 20      # 32 MiB; see docs/design.md for the band
DEFAULT_CPU_SECONDS = 120
DEFAULT_WALL_SECONDS = 180

# RLIMIT_AS bounds one process.  A candidate that shards its accumulator across
# K children is bounded by K x address_space, not by address_space -- measured,
# not assumed: see mutants/m10_fork_spread.py, which defeated an earlier build
# of this grader by doing precisely that.  So the process cap is part of the
# memory ceiling and has to be chosen with it: the pair is only sound while
#
#     max_processes x address_space  <  (address space the cheapest wrong route needs)
#
# At the shipped defaults that is 4 x 32 MiB = 128 MiB against the 384 MiB the
# accumulate-everything route needs (scripts/ceiling_sweep.sh).  Put the other
# way round: sharding that route under a 32 MiB ceiling takes at least twelve
# processes, and the cap is four.  Changing either number without re-checking
# that inequality re-opens the hole.
DEFAULT_MAX_PROCESSES = 4


class _LineSink(io.TextIOBase):
    """File-like adapter turning reference writes into whole lines."""

    def __init__(self, on_line):
        self._on_line = on_line
        self._buf = []

    def write(self, s):
        if "\n" not in s:
            self._buf.append(s)
            return len(s)
        parts = ("".join(self._buf) + s).split("\n")
        self._buf = [parts.pop()]
        for line in parts:
            self._on_line(line)
        return len(s)

    def close_out(self):
        tail = "".join(self._buf)
        if tail:
            self._on_line(tail)


class _Mismatch(Exception):
    def __init__(self, payload):
        Exception.__init__(self, "mismatch")
        self.payload = payload


def _compare(input_path, candidate_path, max_report=3):
    """Stream the reference answer against the candidate's output file.

    Returns (ok, detail).  Neither side is held in memory in full.
    """
    fh = open(candidate_path, "r", encoding="utf-8", errors="replace")
    state = {"n": 0, "diffs": []}

    def norm(rec):
        return json.dumps(rec, separators=(",", ":"), sort_keys=True)

    def on_expected(expected_line):
        state["n"] += 1
        actual_line = fh.readline()
        if actual_line == "":
            raise _Mismatch({
                "kind": "candidate_output_truncated",
                "at_record": state["n"],
                "expected": json.loads(expected_line),
            })
        actual_line = actual_line.rstrip("\n")
        if actual_line == expected_line:
            return
        # Not byte-identical: fall back to a structural comparison so that a
        # different-but-equivalent key order or spacing is not punished.
        try:
            actual = json.loads(actual_line)
        except ValueError:
            raise _Mismatch({
                "kind": "candidate_record_not_json",
                "at_record": state["n"],
                "line": actual_line[:200],
            })
        expected = json.loads(expected_line)
        if norm(actual) == norm(expected):
            return
        state["diffs"].append({
            "at_record": state["n"],
            "expected": expected,
            "actual": actual,
        })
        if len(state["diffs"]) >= max_report:
            raise _Mismatch({
                "kind": "records_differ",
                "first_differences": state["diffs"],
            })

    sink = _LineSink(on_expected)
    try:
        with open(input_path, "r", encoding="utf-8") as inp:
            reference.sessionize(inp, sink)
        sink.close_out()
    except _Mismatch as exc:
        fh.close()
        return False, exc.payload

    if state["diffs"]:
        fh.close()
        return False, {"kind": "records_differ",
                       "first_differences": state["diffs"]}

    extra = fh.readline()
    fh.close()
    if extra != "":
        return False, {
            "kind": "candidate_emitted_extra_records",
            "expected_records": state["n"],
            "first_extra": extra.rstrip("\n")[:200],
        }
    return True, {"records": state["n"]}


def grade(cmd, seed, events, concurrency, address_space, cpu_seconds,
          wall_seconds, keep=None, max_processes=DEFAULT_MAX_PROCESSES):
    work = keep or tempfile.mkdtemp(prefix="gradedenv-")
    os.makedirs(work, exist_ok=True)
    # 0700: the candidate runs as nobody and must not be able to enumerate,
    # replace, or hard-link anything in the grading directory.
    os.chmod(work, 0o700)

    input_path = os.path.join(work, "events.ndjson")
    out_path = os.path.join(work, "candidate.out")
    err_path = os.path.join(work, "candidate.err")

    with open(input_path, "w", encoding="utf-8", newline="\n") as fh:
        stats = generate.generate(seed, events, concurrency, 0.15, 0.22, fh)
    os.chmod(input_path, 0o600)

    limits = sandbox.Limits(
        address_space_bytes=address_space,
        cpu_seconds=cpu_seconds,
        wall_seconds=wall_seconds,
        processes=max_processes,
    )
    run = sandbox.run(cmd, input_path, out_path, err_path, limits, cwd=work)

    reasons = []
    if run["timed_out"]:
        reasons.append("wall-clock timeout after %ds" % wall_seconds)
    if run["term_signal"] is not None:
        reasons.append("killed by signal %d (a SIGKILL here is almost always "
                       "the RLIMIT_AS ceiling)" % run["term_signal"])
    elif run["exit_code"] != 0:
        reasons.append("non-zero exit status %d" % run["exit_code"])

    detail = None
    if not reasons:
        ok, detail = _compare(input_path, out_path)
        if not ok:
            reasons.append("output does not match the reference answer")

    stderr_tail = ""
    try:
        with open(err_path, "r", encoding="utf-8", errors="replace") as fh:
            stderr_tail = fh.read()[-2000:]
    except OSError as exc:
        if exc.errno != errno.ENOENT:
            raise

    cgroup_limit = sandbox.tree_limit_bytes()
    limit_report = limits.as_dict()
    limit_report["max_processes"] = max_processes
    limit_report["cgroup_tree_limit_bytes"] = cgroup_limit
    # What actually bounds the whole process tree.  Without a cgroup this is
    # only the per-process ceiling times the process cap -- weaker, and worth
    # saying out loud in every verdict rather than in a comment nobody reads.
    limit_report["effective_tree_bound_bytes"] = (
        cgroup_limit if cgroup_limit is not None
        else address_space * max_processes)
    limit_report["tree_bound_source"] = (
        "cgroup" if cgroup_limit is not None else "rlimit_as x max_processes")

    verdict = {
        "verdict": "PASS" if not reasons else "FAIL",
        "reasons": reasons,
        "detail": detail,
        "instance": stats,
        "limits": limit_report,
        "resources": {
            "max_rss_bytes": run["max_rss_bytes"],
            "max_rss_mib": round(run["max_rss_bytes"] / (1 << 20), 1),
            "cpu_seconds": round(run["cpu_seconds"], 2),
        },
        "execution": {
            "exit_code": run["exit_code"],
            "term_signal": run["term_signal"],
            "timed_out": run["timed_out"],
            "privileges_dropped": run["privileges_dropped"],
        },
        "candidate_stderr_tail": stderr_tail,
    }

    if keep is None:
        shutil.rmtree(work, ignore_errors=True)
    return verdict


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seed", type=int, default=20260904)
    ap.add_argument("--events", type=int, default=1_200_000)
    ap.add_argument("--concurrency", type=int, default=1_500)
    ap.add_argument("--address-space-mib", type=int,
                    default=DEFAULT_ADDRESS_SPACE >> 20)
    ap.add_argument("--cpu-seconds", type=int, default=DEFAULT_CPU_SECONDS)
    ap.add_argument("--wall-seconds", type=int, default=DEFAULT_WALL_SECONDS)
    ap.add_argument("--max-processes", type=int, default=DEFAULT_MAX_PROCESSES,
                    help="RLIMIT_NPROC for the candidate; bounds fan-out, and "
                         "so is part of the memory ceiling (see grade.py)")
    ap.add_argument("--keep", help="keep the working directory at this path")
    ap.add_argument("cmd", nargs=argparse.REMAINDER,
                    help="the candidate command, after --")
    args = ap.parse_args(argv)

    cmd = [a for a in args.cmd if a != "--"]
    if not cmd:
        ap.error("no candidate command given (put it after --)")

    verdict = grade(
        cmd, args.seed, args.events, args.concurrency,
        args.address_space_mib << 20, args.cpu_seconds, args.wall_seconds,
        keep=args.keep, max_processes=args.max_processes,
    )
    json.dump(verdict, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0 if verdict["verdict"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
